### ISSUE TITLE
Ensure consistency of naming conventions

### ISSUE THREAD

**Issue by AlasdairGray** [QianruZhou333/toco_ontology#10]
We need to be consistent in the naming style used and follow OWL ontology conventions.
- Class names should be in `CamelCase`.
- Property names should be in `camelCase`.

Some of your properties are in `CamelCase` and others are in `word_word`.

**Comment by QianruZhou333** [comment]
Thank you very much for letting me know. Have checked all the entities.

**Comment by AlasdairGray** [comment]
Fixed in commit 6b0c602de2889f21e51ee7f7971041c3f68a3da1
