### ISSUE TITLE
Interface properties

### ISSUE THREAD

**Issue by AlasdairGray** [QianruZhou333/toco_ontology#4]
The following properties need to be changed:
- `net:Channel` --> `net:channel` 
- `net:mode` is missing
- `net:Frequency` --> `net:frequency`

Figure 5 in the paper needs updating too

**Comment by QianruZhou333** [comment]
Thank you very much. Changes has been done.

**Comment by AlasdairGray** [comment]
Figure 5 in the paper needs to be updated to reflect these changes.

**Comment by QianruZhou333** [comment]
Thank you very much. have updated Fig. 5.
