### ISSUE TITLE
Service properties

### ISSUE THREAD

**Issue by AlasdairGray** [QianruZhou333/toco_ontology#5]
The following service properties are missing from the ontology:
- `net:hasStartTime`
- `net:hasEndTime`
- `net:hasStatus`

The ontology has a data property `net:hasServiceStatus`, is this what should be here instead of `net:hasStatus`?

The class `net:Status` is missing from the ontology.

**Comment by QianruZhou333** [comment]
Dear Dr. Gray, 

The properties' name has been changed into 
`net:hasServiceStartTime`
`net:hasServiceEndTime`
`net:hasServiceStatus`

The `net:hasStatus` has been changed to `net:hasServiceStatus` for clarity, for there may be some other kinds of status.

**Comment by AlasdairGray** [comment]
This needs to be reflected in Figure 7 of the paper.

**Comment by QianruZhou333** [comment]
has updated Fig. 7.
