### ISSUE TITLE
Missing property from Listing 2

### ISSUE THREAD

**Issue by AlasdairGray** [QianruZhou333/toco_ontology#7]
In the paper, Listing 2 uses `net:hasAssociation` but this is missing from the ontology.

It also uses two properties `net:hasValue` and `net:hasUnit` which are not defined in the `net` namespace but in the sensordata ontology.

**Comment by QianruZhou333** [comment]
Sorry, I have updated the name to `net:hasWirelessAssociation` but forget to update in the paper. Have revised now.

I have check the om ontology, and it does not have `net:hasValue` or `net:hasUnit` properties. Thus I put  them under the `net` namespace.

**Comment by AlasdairGray** [comment]
We can't just create properties in other ontologies.

Looking at the sensor ontology there is a `hasValue` object property but no `hasUnit` property. 

If you are creating your own then you need to define them in the toco namespace.

**Comment by AlasdairGray** [comment]
I see that you have changed the name space on these. It would be good to update the description as well as you state 'reused from SENSEI observation and measurement ontology.'

**Comment by QianruZhou333** [comment]
Thank you very much. I have revised the description for both `hasUnit` and `hasValue`.
