### ISSUE TITLE
Listing 3 in the paper

### ISSUE THREAD

**Issue by AlasdairGray** [QianruZhou333/toco_ontology#8]
Listing 3 uses a class `ns1:Port`. The namespace `ns1` is not defined. I assume this should be `net` but then `net:Port` is not defined.

The last triple of the example should point to an ontology class for MHz rather than using a string. Something like 
```
ex:s1_h1_bw net:hasUnit http://purl.obolibrary.org/obo/UO_0000325
```
I've not corrected this in the paper

**Comment by QianruZhou333** [comment]
Have changed `net:Port` to `net:Interface` in the paper.

Have changed MHz to `UO:0000325` in the paper.

**Comment by AlasdairGray** [comment]
Paper still has `net:Port` in the listing.

Why is there not a `Port` class, particularly since we have properties `toPort` and `hasPort`?

**Comment by AlasdairGray** [comment]
@QianruZhou333 You should resolve the content of this issue. 
(The issue should be reopened but I can't do that)

**Comment by QianruZhou333** [comment]
Thank you for your comments. I have removed Port class because after thinking over, it turns out that it could be replaced by Interface class. I have changed properties `toPort` to `toInterface`, and `hasPort` to `hasInterface`.

**Comment by AlasdairGray** [comment]
Is there a distinction between a port and an interface? Should port be defined as a subclass of interface?

**Comment by QianruZhou333** [comment]
No, a Port is also an interface. My initial idea is to define Port as wired interface, but then the Oops reports an issue, saying that all the properties are same between Port and Interface, they should be the same concept. Thus, I removed Port.

**Comment by AlasdairGray** [comment]
So would there be a different type of interface, e.g. a wireless interface?

**Comment by QianruZhou333** [comment]
yes, `WLAN` is wireless interface, which is also an subclass of `Interface`.

**Comment by AlasdairGray** [comment]
So we should have `Interface` with subclasses `WLAN` and `Port` which are mutually exclusive as you cannot be a wired connection and wireless simultaneously. 

The properties `toPort` and `fromPort` should have `Port` as the range and domain respectively. Does it make sense to have a `toInterface` and `fromInterface` property? Do these hold in the wireless case?

**Comment by QianruZhou333** [comment]
OK. I will have two subclasses `WLAN` and `Port`. Thank you very much.

Currently I have simply `to` and `from`, whose range and domain are both `Interface`. They can describe both wired and wireless links.

**Comment by AlasdairGray** [comment]
You could consider `toPort` and `fromPort` as sub-properties

**Comment by QianruZhou333** [comment]
Thank you for your comments. I have considered them, but then it seems `to` and `from` are enough to describe the directions of links (wireless and wired) for now. Thus, I did not divide them into sub-properties.
