### ISSUE TITLE
Listing 4 issues

### ISSUE THREAD

**Issue by AlasdairGray** [QianruZhou333/toco_ontology#9]
There are issues with the following properties:
- `net:idle_timeout` --> `net:idleTimeout`
- `net:table_id` --> `net:tableId`
- `net:hard_timeout` --> `net:hardTimeout`
- `net:hasAction` is missing from the ontology
- `net:Output` --> `net:output`

**Comment by QianruZhou333** [comment]
Have changed them all.

**Comment by AlasdairGray** [comment]
I have fixed these in the paper. This issue is now resolved.
